# Конфигурация скрейпера готовой еды

# Настройки браузера
browser:
  headless: true
  timeout: 30000
  user_agents:
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Настройки скрейпинга
scraping:
  parallel_workers: 3
  request_delay_min: 1.0
  request_delay_max: 3.0
  max_retries: 3
  timeout: 30
  scroll_pause_time: 2
  max_scroll_attempts: 50

# Прокси (опционально)
proxy:
  enabled: false
  servers: []
  # Пример:
  # servers:
  #   - "http://user:pass@proxy1.example.com:8080"
  #   - "http://user:pass@proxy2.example.com:8080"

# Настройки по умолчанию
defaults:
  city: "Москва"
  address: "Красная площадь, 1"
  coordinates:
    lat: 55.7558
    lon: 37.6176

# Настройки магазинов
shops:
  samokat:
    name: "Самокат"
    base_url: "https://samokat.ru"
    categories:
      - "готовая-еда"
      - "кулинария"
      - "салаты"
      - "супы"
      - "горячие-блюда"
    selectors:
      product_card: ".product-card"
      product_name: ".product-name"
      product_price: ".price"
      product_link: "a"
      load_more: ".load-more"
      
  lavka:
    name: "Яндекс Лавка"
    base_url: "https://lavka.yandex.ru"
    categories:
      - "gotovaya-eda"
      - "kulinariya"
      - "salaty"
      - "supy"
    selectors:
      product_card: ".product-item"
      product_name: ".product-title"
      product_price: ".product-price"
      product_link: "a"
      
  vkusvill:
    name: "ВкусВилл"
    base_url: "https://vkusvill.ru"
    categories:
      - "gotovaya-eda"
      - "kulinariya"
      - "salaty-i-zakuski"
    selectors:
      product_card: ".catalog-item"
      product_name: ".catalog-item__title"
      product_price: ".catalog-item__price"
      product_link: "a"

# Настройки экспорта
export:
  formats:
    - csv
    - json
    - parquet
  csv_separator: ","
  download_images: false
  images_dir: "images"
  
# Валидация данных
validation:
  min_name_length: 3
  required_fields:
    - "id"
    - "name" 
    - "price"
    - "shop"
    - "url"
  nutrient_completeness_threshold: 0.99

# Логирование
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/scraper.log"
