version: '3.8'

services:
  # Telegram бот
  vkusvill-bot:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TELEGRAM_BOT_TOKEN=$7657488971:AAFNaNjweijtQO6_LQrZ0RJRyEvnLUBkTM4
    command: python3 telegram_bot.py
    restart: unless-stopped

  # Быстрый парсер по адресу
  vkusvill-fast:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python3 address.py "Москва, Тверская улица, 12" 1000
    
  # Полный парсер
  vkusvill-full:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python3 moscow.py 1500
    
  # Интерактивный режим
  vkusvill-shell:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: bash
    stdin_open: true
    tty: true
