# Docker Compose для Ready Food Scraper

version: '3.8'

services:
  scraper:
    build: .
    container_name: ready-food-scraper
    volumes:
      - ./data:/app/data
      - ./images:/app/images
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - BROWSER_HEADLESS=true
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    command: >
      scrape 
      --shop all 
      --city "Москва" 
      --address "Красная площадь, 1"
      --out data/foods.csv
      --format csv json
      --parallel 3
    restart: "no"
    
  # Сервис для разовых задач
  scraper-task:
    build: .
    container_name: ready-food-scraper-task
    volumes:
      - ./data:/app/data
      - ./images:/app/images
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - BROWSER_HEADLESS=true
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    profiles:
      - task
    restart: "no"

  # Сервис для периодического запуска (с cron)
  scraper-cron:
    build: .
    container_name: ready-food-scraper-cron
    volumes:
      - ./data:/app/data
      - ./images:/app/images
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
      - ./scripts/crontab:/etc/cron.d/scraper-cron:ro
    environment:
      - BROWSER_HEADLESS=true
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    profiles:
      - cron
    command: cron -f
    restart: unless-stopped

volumes:
  data:
  images:
  logs:
